name: Main branch build
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install llvm-10-dev libclang-10-dev libclang-cpp10-dev clang cmake
      - uses: actions/checkout@v2
      - uses: m4c0/gha-simple-cmake@c6871761e29e335d2ddd2325f78a29acaf7ef5d6
        with:
          config: Release
          extra_configure_flags: -DLLVM_DIR="/usr/lib/llvm-10"
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu.zip
          path: build

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: m4c0/gha-simple-cmake@c6871761e29e335d2ddd2325f78a29acaf7ef5d6
        with:
          config: Release
          extra_configure_flags: -DLLVM_DIR="/usr/local/opt/llvm"
      - uses: actions/upload-artifact@v2
        with:
          name: macos.zip
          path: build
        
  windows:
    runs-on: windows-latest
    steps:
      - name: Install LLVM
        run: choco install llvm
      - uses: actions/checkout@v2
      - uses: m4c0/gha-simple-cmake@c6871761e29e335d2ddd2325f78a29acaf7ef5d6
        with:
          config: Release
          extra_configure_flags: -DLLVM_DIR="C:/Program Files/LLVM"
      - uses: actions/upload-artifact@v2
        with:
          name: windows.zip
          path: build
        
